In [2]:
import os, json, sys
sys.path.append(os.path.abspath(os.path.join('..')))
import pandas as pd

from seismic_graph import Study

In [3]:
data = []

paths = [
    "/Users/casper/Documents/data/Adam/Astrophage/Astrophage_Data_P3/out/no_DMS__webapp.json"
]

for path in paths:
    with open (path, 'r') as file:
        json_data = json.load(file) 
        data.append(json_data)

study = Study(data=data)
df = study.df

In [4]:
df = study.identify_high_mutation_sequences()

In [4]:
df

,sample,reference,num_aligned,sequence,section,cluster,section_end,section_start,positions,cov,...,sub_C,sub_G,sub_N,sub_T,sub_hist,sub_rate,min_cov,all nt below threshold,has endogenous mutation,endogenous mutation
0,no_DMS,16s_A_6,1021,CCGCCCGTCACGCCACGGAAGTCGGTCCGGCCGGAAGTCCCCGAGC...,full,average,137,1,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",...,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",[768],"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",0.0,True,False,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
1,no_DMS,16s_A_9,1128,ACCGCCCGTCAAGCCACCCGAGTGGGCCAGGGGCGAGGGGGTGGCC...,full,average,133,1,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",...,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",[869],"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",0.0,True,False,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
2,no_DMS,16s_C,3104,GAATCGCGAGTAATCGTAGATCATTAGCGCTACGGTGAAGGTAACC...,full,average,115,1,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",...,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[1760, 15]","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",1253.0,True,False,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
3,no_DMS,16s_C_14,3551,GATAAACCTTTAGCAATAAACGAAAGTTTAACTAAGCCATACTAAC...,full,average,162,1,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",...,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[3082, 59]","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",1306.0,True,False,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
4,no_DMS,16s_H,1182,CCGCCCGTCAAAGCACCCGAGTGAGGTCCGGATGAGGCCACCACAC...,full,average,128,1,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",...,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",[805],"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",0.0,True,False,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,no_DMS,tRNA_tdbR00000617-Nanoarchaeum_equitans-160232...,5001,AGCCCCGTGGTGTAGCGGCCTAGCATGCGGGGTTTTGGTCCCCGTG...,full,average,76,1,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",...,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[4593, 31]","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",3776.0,True,False,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
307,no_DMS,tRNA_tdbR00000618-Candida_albicans-5476-Leu-CAG,6112,GATACGATGGCCGAGTGGTTAAGGCGAAGGATGCAGGTTCCTTTGG...,full,average,85,1,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",...,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[5464, 77, 1]","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",2718.0,True,False,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
308,no_DMS,tRNA_tdbR00000620-Toxoplasma_gondii-5811-Ini-CAU,2264,AGCACCGTAGCTCAGTGGGAGAGTGGGGGGCTCATAACCCCCAGGT...,full,average,72,1,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",...,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[2019, 6]","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",1791.0,True,False,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
309,no_DMS,tRNA_tdbR00000621-Nicotiana_rustica-4093-Cys-GCA,1030,GGGTCCATAGCTCAGTGGTAGAGCATTTGACTGCAGATCAAGAGGT...,full,average,75,1,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",...,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",[950],"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",0.0,True,False,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
310,no_DMS,tRNA_tdbR00000622-Nicotiana_rustica-4093-Cys-GCA,2722,GGCGACATGGCCGAGTGGTAAGGCAGAGGACTGCAAATCCTTTTTT...,full,average,75,1,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",...,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[2402, 20]","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",1605.0,True,False,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."

In [5]:
# Count the number of sequences with all bases below the threshold vs. those that are not
below_threshold_counts = df['all nt below threshold'].value_counts()
endogenous_mut_counts = df['has endogenous mutation'].value_counts()

print("Sequences with all nucleotides below threshold:", below_threshold_counts.get(True, 0))
print("Sequences with some nucleotides above threshold:", below_threshold_counts.get(False, 0))

print("Sequences with endogenous mutation:", endogenous_mut_counts.get(True, 0))

Sequences with all nucleotides below threshold: 304
Sequences with some nucleotides above threshold: 7
Sequences with endogenous mutation: 2

In [5]:
len(df)

311

In [6]:
df[df['has endogenous mutation']==True]

,sample,reference,num_aligned,sequence,section,cluster,section_end,section_start,positions,cov,...,sub_C,sub_G,sub_N,sub_T,sub_hist,sub_rate,min_cov,all nt below threshold,has endogenous mutation,endogenous mutation
132,no_DMS,RNaseP_H_2,3055,GAATTCAACGTATAAACGAGACACATGCATATATTTTGTTATGTGT...,full,average,120,1,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",...,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[670, 1879, 18]","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",1467.3,False,True,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."
133,no_DMS,RNaseP_K_2,4388,GAACACAGCGAGACAACAATCGCCAGGGGCTTCGGCCCTGATTCTC...,full,average,219,1,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",...,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[1160, 1820, 35]","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...",5032.6,False,True,"[nan, nan, nan, nan, nan, nan, nan, nan, nan, ..."

In [6]:
fig = study.mutation_fraction_identity(
    sample="no_DMS",
    reference="RNaseP_H_2"
)["fig"]
fig.write_image("/Users/casper/Downloads/newplot4.png", format="png", scale=2, width=1920, height=1080)

In [7]:
fig = study.mutation_fraction_identity(
    sample="no_DMS",
    reference="RNaseP_K_2"
)["fig"]

fig.write_image("/Users/casper/Downloads/newplot5.png", format="png", scale=2, width=1920, height=1080)

In [4]:
fig = study.max_sub_rate_histogram()['fig']
fig.write_image("/Users/casper/Downloads/newplot3.png", format="png", scale=2, width=1920, height=1080)